### ISSUE TITLE
Crashes on Server for muiltiple clients.

### ISSUE THREAD

**Issue by RetrosServer** [RHSMODS/statusquo#924] opened 2024-07-21 11:06 UTC
This error occurs and then usualy players start getting kicked/crashing.

If you need more info let me know.

[rhs crash.txt](https://github.com/user-attachments/files/16323978/rhs.crash.txt)

**Comment by ajvorobiev** [comment] 2024-07-24 21:35
> This error occurs and then usualy players start getting kicked/crashing.
> 
> If you need more info let me know.
> 
> [rhs crash.txt](https://github.com/user-attachments/files/16323978/rhs.crash.txt)

which error? Ive looked into the log and the last error shown is:

```
19:16:55.552      INVENTORY (E): Couldn't insert item @"ENTITY:4611686018427418353" ('GenericEntity','Assets/Weapons/Grenades/RDG2/Smoke_RDG2.xob') at <0.000000 0.000000 0.000000> @"{77EAE5E07DC4678A}Prefabs/Weapons/Grenades/Smoke_RDG2.et" into storage @"ENTITY:4611686018427418324" ('GenericEntity','Assets/Characters/Vests/Vest_Common/rhs_equipment_empty.xob') at <4922.762207 171.900528 7044.140137> @"{20CFD20350444288}Prefabs/Characters/Vests/Vest_Ratnik_6B45/Variants/Vest_Ratnik_6B45_rifleman.et" while spawning initial items inside the storage.
```

and this one is normal to appear and should not cause crashes. We do know that Kh55 can cause crashes sometimes randomly. Unless you can provide more info I will have to close this as unreplicatable.

**Comment by RetrosServer** [comment] 2024-07-25 23:19
i will see if i can get players to crash again but i will usually see that error start spamming and then a player crashes around the same time.

**Comment by RetrosServer** [comment] 2024-07-26 00:05
Here are the logs from the last few days i have removed IP's of players i have uplaoded it as a json.
[Server logs.json](https://github.com/user-attachments/files/16385012/Server.logs.json)

**Comment by ajvorobiev** [comment] 2024-08-05 13:54
Must be a memory leak in the game somewhere. Can't really do anything solid because your log has like 30 mods loaded so that is no go on reproduction. We know of several RHS related crashes here and there which we are actively fixing, lets just hope it is one of these.

**Closed by ajvorobiev** 2024-08-05 13:54 UTC

**Comment by odkupiciel375** [comment] 2024-08-05 14:32
@RetrosServer in addition to that server logs are nearly useless when client crashes as then u need crash.log from that client as even their console.log may not have necessary information about what caused the crash
