### ISSUE TITLE
no vehicles in the select menu 

### ISSUE THREAD

**Issue by sovjetpikachu** [RHSMODS/statusquo#1000] opened 2024-10-12 19:45 UTC
soo basically i was just playing an testing out the mod if id liked it or not i checked the outfits and guns i liked it i decide to grab a vehicle to do some missions and i couldn't cus there was no car and it was the only mod installed i played it on the conflict-Everon (RHS) scenario and on the normal version i had everything like cars and such but of course not the things the mod came with 
![Screenshot 2024-10-12 213939](https://github.com/user-attachments/assets/53d43987-6d3b-43ff-a220-2ba32fccc513)
  

EDIT: i can spawn them via game master just not the menus from the spawn stations 
EDIT2: i found out its the same for ai personal and helicopter

**Comment by ajvorobiev** [comment] 2024-10-28 16:57
Duplicate of #988

**Closed by ajvorobiev** 2024-10-28 16:57 UTC
