### ISSUE TITLE
(1.2) M4A1 Ergo AFG hand position

### ISSUE THREAD

**Issue by Cyborgmatt** [RHSMODS/statusquo#837] opened 2024-06-25 03:15 UTC
The M4A1 Ergo with the AFG has some animation issues with the hand placement.

![image](https://github.com/RHSMODS/statusquo/assets/3114217/9a55baed-9cff-4300-bfbc-885b8410b015)

**Comment by ajvorobiev** [comment] 2024-07-01 22:11
duplicate of #779

**Closed by ajvorobiev** 2024-07-01 22:11 UTC
Labels: duplicate
