### ISSUE TITLE
(1.2) 6 Rib Rail Cover detach string

### ISSUE THREAD

**Issue by Cyborgmatt** [RHSMODS/statusquo#836] opened 2024-06-25 03:06 UTC
The 6 Rib Rail Cover is missing its detach string.

![image](https://github.com/RHSMODS/statusquo/assets/3114217/9a7d5b29-5a4c-4d6d-b92e-a6015829c50d)

**Comment by odkupiciel375** [comment] 2024-06-26 04:38
duplicate of https://github.com/RHSMODS/statusquo/issues/738

**Closed by odkupiciel375** 2024-06-26 04:38 UTC
