### ISSUE TITLE
IR Illuminator dont move with ALT key

### ISSUE THREAD

**Issue by Josem27** [RHSMODS/statusquo#362] opened 2023-07-11 17:27 UTC
When u use the IR illuminator of the nightvision, looks like it don't follow the head move with the ALT key

https://github.com/RHSMODS/statusquo/assets/126608382/ea528875-bf25-4029-8a5e-09cdd11a321b

**Comment by odkupiciel375** [comment] 2023-07-14 08:19
technically speaking it's not a bug since this functionality is wip and current implementation is more of a PoC but i will close this issue when i will commit that functionality

**Closed** 2023-07-19 17:20 UTC
Labels: bug, TestNeeded
