### ISSUE TITLE
MSV Flora Faction - Floating Solider Patches

### ISSUE THREAD

**Issue by TPMTactical** [RHSMODS/statusquo#1040] opened 2024-12-23 08:51 UTC
Game Version: 1.2.1.169 (Stable)
Mod Version: 0.10.3948 (Stable)
Issue/Bug: MSV Flora Faction have floating shoulder patches (reference attached image)
![Screenshot 2024-12-23 084254](https://github.com/user-attachments/assets/d944476a-40ca-4515-bea8-74d264f4e643)

**Comment by ajvorobiev** [comment] 2024-12-28 13:59
Strange, this was fixed in 3835 already and I cannot reproduce it anymore.

**Closed by ajvorobiev** 2024-12-28 13:59 UTC
Labels: invalid
