### ISSUE TITLE
Weird bending at the elbow for rifle animation pose

### ISSUE THREAD

**Issue by Vergyy** [RHSMODS/statusquo#808] opened 2024-05-27 00:23 UTC
![image](https://github.com/RHSMODS/statusquo/assets/107449389/547a73c9-4a69-4a76-8c51-f13109ae2bd2)
![image](https://github.com/RHSMODS/statusquo/assets/107449389/2677a538-983d-4468-9b80-b7ece8afd4bc)

**Comment by ajvorobiev** [comment] 2024-07-08 12:33
Duplicate of #779

**Closed by ajvorobiev** 2024-07-08 12:33 UTC
Labels: bug, weapon, BLUFOR, 1.2
